// payout-request — the SOL claim queue a holder opens and an operator works.
//
// ===========================================================================
// THIS IS NOT request-payout. THE NAMES ARE ONE HYPHEN APART AND THE MONEY IS
// NOT THE SAME MONEY.
// ===========================================================================
//   request-payout   — the OPERATOR recording a $xNFT sweep out of the treasury
//                      to the dev wallet. A signature already exists; the row is
//                      settled later by confirm-payout re-reading the chain.
//                      Money leaving the protocol.
//   payout-request   — a HOLDER asking to be paid accrued yield, in SOL, out of
//                      pump.fun creator fees. Money arriving at a user, sent BY
//                      HAND from a wallet this backend holds no key for.
//
// They are separate tables, separate functions and separate vocabularies for
// exactly that reason: confusing them would let a holder's claim be settled by a
// transaction that paid the operator.
//
// ===========================================================================
// NOTHING HERE MOVES SOL, AND NOTHING HERE CAN
// ===========================================================================
// There is no key, no RPC call and no transfer on this path. `status = 'paid'` is
// an operator writing down a transfer they performed, together with its
// signature, so anybody can go and check it. That is the only verification
// available when the paying key never comes near this system, and it is published
// rather than dressed up as a confirmation this backend performed.
//
// ===========================================================================
// WHAT BOUNDS A CLAIM
// ===========================================================================
// The amount comes from the browser, because accrual is computed there from a
// deterministic function of hire time and skills. `public.request_payout` does
// not trust that number — it recomputes the wallet's maximum possible accrual
// from `principal x apy x tenure` across the xployees the database says it owns,
// subtracts everything already claimed, and refuses anything above it. The bound
// is deliberately generous (it ignores rentals redirecting yield), so it can only
// ever be too permissive rather than too strict: a holder is never refused money
// they are owed because two languages rounded differently. An operator reviews
// every ticket, and that review is the actual control.
import { callRpc } from '../_shared/db.ts'
import { loadPlatformConfig } from '../_shared/env.ts'
import { resolveCaller, writerRefusal, type WriterResult } from '../_shared/auth.ts'
import { errorResponse, fnError, isFnError, jsonResponse, readJsonBody, serveSafely } from '../_shared/http.ts'

/** CLAIM_ID_RE from src/lib/earnings.ts. Crockford base32 with I, L, O and U removed. */
const CLAIM_ID = /^XN-[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}$/

function money(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : null
}

Deno.serve(serveSafely(async (request: Request): Promise<Response> => {
  const body = await readJsonBody(request)
  if (isFnError(body)) return errorResponse(body)

  const config = loadPlatformConfig()
  if (isFnError(config)) return errorResponse(config)

  const caller = await resolveCaller(config, request)
  if (isFnError(caller)) return errorResponse(caller)

  const action = typeof body.action === 'string' ? body.action : 'request'
  const claimId = typeof body.claimId === 'string' ? body.claimId.trim() : ''

  // ---- the holder's side --------------------------------------------------

  if (action === 'request') {
    if (!CLAIM_ID.test(claimId)) {
      return errorResponse(
        fnError('bad-request', 'Post the `claimId` generated by newClaimId() in src/lib/earnings.ts.'),
      )
    }
    const amountUsd = money(body.amountUsd)
    const solUsd = money(body.solUsd)
    if (amountUsd === null) {
      return errorResponse(fnError('bad-request', '`amountUsd` is a positive number.'))
    }
    // The rate is required rather than defaulted. A ticket settled months later
    // has to be readable without wondering what SOL was worth that afternoon, and
    // a server-side default would record a rate the requester never saw.
    if (solUsd === null) {
      return errorResponse(fnError('bad-request', '`solUsd` is the SOL price the amount was quoted at.'))
    }

    const result = await callRpc<WriterResult>(config, 'request_payout', {
      p_user_id: caller.userId,
      p_claim_id: claimId,
      p_amount_usd: amountUsd,
      p_sol_usd: solUsd,
    })
    if (isFnError(result)) return errorResponse(result)
    const refusal = writerRefusal(result)
    if (refusal) return errorResponse(refusal)

    return jsonResponse({
      ok: true,
      action: 'request',
      // 'duplicate' when the same claim id was already queued. A retried post
      // finds its own ticket rather than opening a second one.
      outcome: result.outcome ?? 'queued',
      claimId,
      amountUsd: result.amount_usd ?? amountUsd,
      amountLamports: result.amount_lamports ?? null,
      note: 'Queued for an operator. Nothing is paid automatically — SOL is sent by hand and the signature is recorded here.',
    })
  }

  if (action === 'cancel') {
    if (!CLAIM_ID.test(claimId)) {
      return errorResponse(fnError('bad-request', 'Post the `claimId` to withdraw.'))
    }
    const result = await callRpc<WriterResult>(config, 'cancel_payout_request', {
      p_user_id: caller.userId,
      p_claim_id: claimId,
    })
    if (isFnError(result)) return errorResponse(result)
    const refusal = writerRefusal(result)
    if (refusal) return errorResponse(refusal)
    return jsonResponse({ ok: true, action: 'cancel', claimId })
  }

  // ---- the operator's side ------------------------------------------------
  //
  // Authority is a row in `public.operators`, checked in SQL against the wallet
  // this session proved it holds. It is not checked here, and that is deliberate:
  // an authorisation performed in an Edge Function is an authorisation that a
  // second Edge Function can forget to perform.

  if (action === 'resolve') {
    if (!CLAIM_ID.test(claimId)) {
      return errorResponse(fnError('bad-request', 'Post the `claimId` to resolve.'))
    }
    const status = body.status
    if (status !== 'approved' && status !== 'rejected' && status !== 'paid') {
      return errorResponse(fnError('bad-request', '`status` is "approved", "rejected" or "paid".'))
    }

    const result = await callRpc<WriterResult>(config, 'resolve_payout_request', {
      p_user_id: caller.userId,
      p_claim_id: claimId,
      p_status: status,
      p_note: typeof body.note === 'string' ? body.note.slice(0, 500) : null,
      // Both required by the SQL writer when marking paid, and deliberately not
      // defaulted here: a settled row without its evidence is a claim of payment
      // nobody can check and nobody can disprove.
      p_signature: typeof body.signature === 'string' ? body.signature.trim() : null,
      p_lamports: typeof body.lamports === 'string' ? body.lamports.trim() : null,
    })
    if (isFnError(result)) return errorResponse(result)
    const refusal = writerRefusal(result)
    if (refusal) return errorResponse(refusal)

    return jsonResponse({ ok: true, action: 'resolve', claimId, status })
  }

  return errorResponse(fnError('bad-request', '`action` must be "request", "cancel" or "resolve".'))
}))
