-- xNFTs index — payout_requests: the SOL claim queue the admin desk works.
--
-- ===========================================================================
-- THIS IS NOT public.payouts. READ THIS BEFORE USING EITHER.
-- ===========================================================================
-- Two queues exist and they are about different money moving in different
-- directions. Confusing them would let a holder's claim be settled by a
-- transaction that paid the dev wallet, so they are separate tables with
-- separate writers and no shared status vocabulary.
--
--   public.payouts          — the OPERATOR sweeping $xNFT fees out of the
--                             treasury to the dev wallet. One signer, one
--                             destination read from configuration, settled by
--                             `confirm-payout` re-reading the chain. Money
--                             leaving the protocol.
--   public.payout_requests  — a HOLDER asking to be paid their accrued yield, in
--                             SOL, out of pump.fun creator fees. Money arriving
--                             at a user. There is no automated settlement and
--                             there is not going to be one: an operator sends the
--                             SOL by hand from a wallet this backend does not
--                             hold a key for, and then records the signature.
--
-- ===========================================================================
-- WHAT A REQUEST IS AND IS NOT
-- ===========================================================================
-- It is a ticket. `src/lib/earnings.ts` computes the claimable figure from
-- accrual — a pure function of hire time and skills — and mints a human-readable
-- claim id (`XN-A3K7M-9PQR2`, Crockford base32 with I/L/O/U removed so it
-- survives being read down a phone line). The row here is that ticket.
--
-- It is NOT an instruction to a machine. Nothing in this schema can move SOL, no
-- function here signs anything, and `status = 'paid'` is a statement an operator
-- makes about a transfer they performed — recorded with its signature so anybody
-- can go and check it, which is the only kind of verification available when the
-- paying key never comes near this system.
--
-- ===========================================================================
-- THE AMOUNT
-- ===========================================================================
-- Two figures, and the distinction is the same one `public.payouts` draws.
--
--   `amount_usd`      — the USD the requester was shown when they clicked. A
--                       display notional in exact decimal; it gates nothing.
--   `amount_lamports` — the SOL figure, in raw units as a digit string. This is
--                       the money column, and it is a u64_text for the reason the
--                       domain exists: PostgREST serialises numeric as a JSON
--                       number and a lamport figure that has been through a
--                       double is a lamport figure that is wrong.
--   `paid_lamports`   — what actually went out, filled in with the signature.
--                       NULL until then, so "requested" and "paid" can never be
--                       read as the same number.

create table public.payout_requests (
  -- The claim id IS the primary key. It is what a support ticket is resolved by
  -- and what a user reads out loud, so giving the row a uuid alongside it would
  -- create a second identity for the same thing and an opportunity for the two to
  -- be quoted at each other.
  --
  -- The pattern is CLAIM_ID_RE from src/lib/earnings.ts, restated here rather
  -- than assumed: an id generated by some other client still has to look like one
  -- of ours or it cannot enter the queue.
  claim_id text primary key check (claim_id ~ '^XN-[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}$'),

  wallet public.base58_address not null,

  amount_usd      numeric(20, 2)   not null check (amount_usd > 0),
  amount_lamports public.u64_text  not null,
  -- The rate the quote was made at, so a settled ticket can be read back years
  -- later without wondering what SOL was worth that afternoon. Display only.
  sol_usd_at_request numeric(20, 6) not null check (sol_usd_at_request > 0),

  --   pending   — in the queue, nobody has looked at it.
  --   approved  — an operator has accepted it and intends to pay. Not money yet.
  --   paid      — SOL was sent; the signature is on the row.
  --   rejected  — an operator declined it, with a reason.
  --   cancelled — the requester withdrew it before it was settled.
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'paid', 'rejected', 'cancelled')),

  -- The SOL transfer. Not a foreign key to anything and not verified by this
  -- backend — it is a Solana signature on a transaction sent from a wallet whose
  -- key lives with the operator. Unique, so one transfer cannot be used to settle
  -- two tickets.
  signature     public.tx_signature unique,
  paid_lamports public.u64_text,

  -- Free text from whoever worked the ticket. Visible to the requester, so it is
  -- an explanation rather than an internal note — a rejection with no sentence
  -- attached is how a support queue turns into a grievance.
  operator_note text check (operator_note is null or length(operator_note) <= 500),

  requested_at timestamptz not null default now(),
  reviewed_at  timestamptz,
  paid_at      timestamptz,
  updated_at   timestamptz not null default now(),

  -- 'paid' is reachable only with the evidence. Three columns move together or
  -- the row is refused, which makes "we only mark it paid once it is paid" a
  -- property of the table rather than of the endpoint that writes it.
  constraint payout_requests_paid_has_evidence check (
    (status = 'paid' and signature is not null and paid_lamports is not null and paid_at is not null)
    or (status <> 'paid' and signature is null and paid_lamports is null and paid_at is null)
  ),
  -- A rejection carries its reason. Without this, a declined ticket can sit in
  -- somebody's history with no explanation and no way to get one.
  constraint payout_requests_rejection_has_reason check (
    status <> 'rejected' or operator_note is not null
  ),
  -- Anything an operator has touched says when.
  constraint payout_requests_reviewed_has_timestamp check (
    status in ('pending', 'cancelled') or reviewed_at is not null
  )
);

-- ONE OPEN REQUEST PER WALLET, as a constraint rather than as a check somebody
-- performs. This is the same shape as the mint reservation index and it is doing
-- the same job: two clicks arriving together cannot both open a ticket, so a
-- wallet cannot get its accrued yield queued twice and paid twice by an operator
-- working down a list.
create unique index payout_requests_one_open_per_wallet
  on public.payout_requests (wallet) where status in ('pending', 'approved');

create index payout_requests_queue_idx  on public.payout_requests (status, requested_at asc);
create index payout_requests_wallet_idx on public.payout_requests (wallet, requested_at desc);

comment on table public.payout_requests is
  'Holders asking to be paid their accrued yield in SOL from pump.fun creator fees. A ticket, not an instruction: nothing here can move SOL, and ''paid'' is an operator recording a transfer they made by hand, with its signature.';
comment on column public.payout_requests.claim_id is
  'The id a human reads out. Crockford base32 with I, L, O and U removed so 1/I and 0/O are never both drawable — see CLAIM_ID_RE in src/lib/earnings.ts.';
comment on column public.payout_requests.signature is
  'The SOL transfer an operator sent. This backend does NOT verify it — the paying key never touches this system — so it is published for anyone to check rather than presented as something the server confirmed.';
comment on column public.payout_requests.amount_lamports is
  'The money column, in raw units. amount_usd beside it is a display notional and gates nothing.';

-- ---------------------------------------------------------------------------
-- Operator identity
-- ---------------------------------------------------------------------------

-- Who may work the queue. A table rather than a hard-coded address, so adding or
-- removing an operator is an INSERT and not a deploy — and so the answer to "who
-- could have marked this paid" is a query rather than an archaeology exercise
-- through old builds.
--
-- Seeded EMPTY on purpose, which is the same discipline as every deployment
-- constant in src/lib/spl.ts: with no rows, every operator action refuses. An
-- operator is added deliberately, once, by somebody with database access.
create table public.operators (
  wallet     public.base58_address primary key,
  label      text,
  can_pay    boolean not null default true,
  added_at   timestamptz not null default now(),
  removed_at timestamptz
);

comment on table public.operators is
  'Wallets allowed to work the payout queue. Ships EMPTY, so every operator path refuses until somebody with database access adds a row — the same "unset means disabled" rule the deployment constants follow.';

create or replace function public.is_operator(p_wallet text)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.operators
     where wallet = p_wallet and removed_at is null and can_pay
  )
$$;

-- ---------------------------------------------------------------------------
-- request_payout — the holder's side
-- ---------------------------------------------------------------------------

-- The wallet comes from the session, never from the caller. The claim id and the
-- amount DO come from the client, and that is worth being honest about rather
-- than dressing up: accrual is computed in the browser from a deterministic
-- function of hire time and skills, so the figure a request carries is the
-- browser's arithmetic.
--
-- What the database enforces around it:
--
--   * the requester owns at least one xployee — you cannot claim yield from an
--     empty wallet;
--   * the amount does not exceed what this wallet's holdings could possibly have
--     accrued, recomputed HERE from `principal x apy x tenure` and net of
--     everything already requested. This is the check that matters: it does not
--     trust the client's number, it bounds it;
--   * one open ticket per wallet, by unique index.
--
-- The bound is generous by construction — it ignores rentals redirecting yield,
-- so it can only ever be too permissive rather than too strict, and a holder is
-- never refused money they are owed because of a rounding difference between two
-- languages. An operator still reviews every ticket. That is the actual control,
-- and this function's job is to stop the queue filling with impossible numbers.
create or replace function public.request_payout(
  p_user_id     uuid,
  p_claim_id    text,
  p_amount_usd  numeric,
  p_sol_usd     numeric
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_wallet    text;
  v_accrued   numeric;
  v_requested numeric;
  v_lamports  numeric;
  v_crew      integer;
begin
  v_wallet := public.actor_wallet(p_user_id);
  if v_wallet is null then
    return jsonb_build_object('ok', false, 'code', 'no-wallet',
      'message', 'This session has no linked wallet. Nothing was requested.');
  end if;
  if p_claim_id is null or p_claim_id !~ '^XN-[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}$' then
    return jsonb_build_object('ok', false, 'code', 'bad-claim-id',
      'message', 'That is not a claim id. Nothing was requested.');
  end if;
  if p_amount_usd is null or p_amount_usd <= 0 then
    return jsonb_build_object('ok', false, 'code', 'bad-amount',
      'message', 'A request has to be for a positive amount. Nothing was requested.');
  end if;
  if p_sol_usd is null or p_sol_usd <= 0 then
    return jsonb_build_object('ok', false, 'code', 'bad-rate',
      'message', 'A request has to carry the SOL price it was quoted at. Nothing was requested.');
  end if;

  -- Idempotent on the claim id: a retried post finds its own ticket rather than
  -- opening a second one, and the partial unique index would refuse the second
  -- anyway.
  if exists (select 1 from public.payout_requests where claim_id = p_claim_id) then
    return jsonb_build_object('ok', true, 'outcome', 'duplicate', 'claim_id', p_claim_id);
  end if;

  select count(*),
         coalesce(sum(
           x.principal * x.apy
             * greatest(0, extract(epoch from (now() - x.hired_at))) / (86400 * 365)
         ), 0)
    into v_crew, v_accrued
    from public.xployees x
   where x.owner = v_wallet and x.hired_at is not null;

  if v_crew = 0 then
    return jsonb_build_object('ok', false, 'code', 'no-crew',
      'message', 'This wallet holds no xployees, so nothing has accrued to it. Nothing was requested.');
  end if;

  -- Everything already spoken for. A rejected ticket releases its amount back;
  -- anything else — pending, approved or paid — is money this wallet has already
  -- asked for, matching requestedUsd() in src/lib/earnings.ts.
  select coalesce(sum(amount_usd), 0) into v_requested
    from public.payout_requests
   where wallet = v_wallet and status <> 'rejected' and status <> 'cancelled';

  if p_amount_usd > greatest(0, v_accrued - v_requested) + 0.01 then
    return jsonb_build_object(
      'ok', false, 'code', 'over-accrual',
      'message', format(
        'This wallet''s crew has accrued about $%s and $%s of that is already spoken for, so $%s cannot be claimed. Nothing was requested.',
        round(v_accrued, 2), round(v_requested, 2), round(p_amount_usd, 2))
    );
  end if;

  if exists (select 1 from public.payout_requests where wallet = v_wallet and status in ('pending', 'approved')) then
    return jsonb_build_object('ok', false, 'code', 'already-open',
      'message', 'This wallet already has a request in the queue. It has to be settled before another can be opened.');
  end if;

  -- USD to lamports at the quoted rate, floored. Flooring is the deliberate
  -- direction here as everywhere else in this codebase: a request never asks for
  -- a lamport more than the quote supports.
  v_lamports := trunc(p_amount_usd / p_sol_usd * 1000000000);

  insert into public.payout_requests (claim_id, wallet, amount_usd, amount_lamports, sol_usd_at_request)
  values (p_claim_id, v_wallet, round(p_amount_usd, 2), v_lamports::text, p_sol_usd);

  return jsonb_build_object(
    'ok', true, 'outcome', 'queued',
    'claim_id', p_claim_id,
    'amount_usd', round(p_amount_usd, 2),
    'amount_lamports', v_lamports::text
  );
end;
$$;

-- The requester withdrawing their own ticket. Only while it is still open — once
-- an operator has paid it there is a transfer on a ledger somewhere, and a row
-- that says 'cancelled' next to a signature would be a lie about money that moved.
create or replace function public.cancel_payout_request(p_user_id uuid, p_claim_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_wallet text;
  v_hit    integer;
begin
  v_wallet := public.actor_wallet(p_user_id);
  if v_wallet is null then
    return jsonb_build_object('ok', false, 'code', 'no-wallet',
      'message', 'This session has no linked wallet. Nothing was changed.');
  end if;

  update public.payout_requests
     set status = 'cancelled', updated_at = now()
   where claim_id = p_claim_id and wallet = v_wallet and status = 'pending';
  get diagnostics v_hit = row_count;

  if v_hit = 0 then
    return jsonb_build_object('ok', false, 'code', 'not-cancellable',
      'message', 'That claim is not this wallet''s, or it is no longer pending. Nothing was changed.');
  end if;
  return jsonb_build_object('ok', true, 'claim_id', p_claim_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- resolve_payout_request — the operator's side
-- ---------------------------------------------------------------------------

-- Approve, reject, or record a payment. The operator is resolved from the session
-- and checked against `public.operators`, so authority is a row in a table rather
-- than a comparison against a constant compiled into a bundle.
--
-- Marking a ticket paid REQUIRES the signature and the lamport figure. Not
-- because this backend can verify them — it cannot, the paying key is not here —
-- but because a settled row without them is unauditable, and an unauditable
-- payout record is worse than none: it is a claim of payment that nobody can
-- check and nobody can disprove.
create or replace function public.resolve_payout_request(
  p_user_id   uuid,
  p_claim_id  text,
  p_status    text,
  p_note      text default null,
  p_signature text default null,
  p_lamports  text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_operator text;
  v_row      public.payout_requests;
begin
  v_operator := public.actor_wallet(p_user_id);
  if v_operator is null or not public.is_operator(v_operator) then
    -- One sentence for "not signed in" and "not an operator" alike. Telling an
    -- unauthorised caller which of the two they failed is telling them how to
    -- fix it.
    return jsonb_build_object('ok', false, 'code', 'not-operator',
      'message', 'This session is not an operator of the payout queue. Nothing was changed.');
  end if;
  if p_status not in ('approved', 'rejected', 'paid') then
    return jsonb_build_object('ok', false, 'code', 'bad-status',
      'message', 'An operator approves, rejects or records payment. Nothing was changed.');
  end if;

  select * into v_row from public.payout_requests where claim_id = p_claim_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'not-found',
      'message', 'No claim with that id. Nothing was changed.');
  end if;
  -- Settlement is one-way. A paid ticket cannot be re-opened, re-approved or
  -- rejected after the fact — the transfer already happened.
  if v_row.status not in ('pending', 'approved') then
    return jsonb_build_object('ok', false, 'code', 'already-settled',
      'message', format('That claim is already %s. Nothing was changed.', v_row.status));
  end if;

  if p_status = 'rejected' and nullif(btrim(coalesce(p_note, '')), '') is null then
    return jsonb_build_object('ok', false, 'code', 'reason-required',
      'message', 'A rejection needs a reason the requester can read. Nothing was changed.');
  end if;

  if p_status = 'paid' then
    if p_signature is null or p_signature !~ '^[1-9A-HJ-NP-Za-km-z]{64,88}$' then
      return jsonb_build_object('ok', false, 'code', 'signature-required',
        'message', 'Recording a payment needs the signature of the SOL transfer. Nothing was changed.');
    end if;
    if p_lamports is null or p_lamports !~ '^(0|[1-9][0-9]{0,19})$' or p_lamports = '0' then
      return jsonb_build_object('ok', false, 'code', 'amount-required',
        'message', 'Recording a payment needs the lamports actually sent. Nothing was changed.');
    end if;
    if exists (select 1 from public.payout_requests where signature = p_signature and claim_id <> p_claim_id) then
      return jsonb_build_object('ok', false, 'code', 'signature-reused',
        'message', 'That signature already settles another claim. One transfer settles one ticket. Nothing was changed.');
    end if;

    update public.payout_requests
       set status = 'paid',
           signature = p_signature,
           paid_lamports = p_lamports,
           paid_at = now(),
           reviewed_at = coalesce(reviewed_at, now()),
           operator_note = coalesce(nullif(btrim(coalesce(p_note, '')), ''), operator_note),
           updated_at = now()
     where claim_id = p_claim_id;
  else
    update public.payout_requests
       set status = p_status,
           reviewed_at = now(),
           operator_note = coalesce(nullif(btrim(coalesce(p_note, '')), ''), operator_note),
           updated_at = now()
     where claim_id = p_claim_id;
  end if;

  return jsonb_build_object('ok', true, 'claim_id', p_claim_id, 'status', p_status, 'operator', v_operator);
end;
$$;

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

-- The admin desk subscribes to this queue, so a ticket opened while the operator
-- is looking at the page appears without a refresh.
--
-- `replica identity full` so an UPDATE payload carries the PREVIOUS row as well
-- as the new one. Without it Postgres publishes only the primary key for the old
-- tuple, and a desk watching for "pending became paid" would have to re-query to
-- find out what a row changed FROM — which is a round trip per event and a race
-- with the next update.
--
-- Note that realtime respects RLS for the anon key: an unauthenticated browser
-- receives these events only because the read policy in 20260806091100 publishes
-- the queue, and every column it can see is one it could already have selected.
alter table public.payout_requests replica identity full;
alter table public.payouts         replica identity full;

do $$
begin
  -- The publication exists on every Supabase project, but this migration should
  -- not fail on a bare Postgres that has never had Realtime enabled.
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.payout_requests;
    alter publication supabase_realtime add table public.payouts;
    alter publication supabase_realtime add table public.mints;
  else
    raise notice 'publication supabase_realtime does not exist; realtime was not configured';
  end if;
exception
  when duplicate_object then
    raise notice 'tables are already in the supabase_realtime publication';
end;
$$;

-- ---------------------------------------------------------------------------
-- Execution grants
-- ---------------------------------------------------------------------------

revoke all on function public.is_operator(text) from public, anon, authenticated;
revoke all on function public.request_payout(uuid, text, numeric, numeric) from public, anon, authenticated;
revoke all on function public.cancel_payout_request(uuid, text) from public, anon, authenticated;
revoke all on function public.resolve_payout_request(uuid, text, text, text, text, text) from public, anon, authenticated;

grant execute on function public.is_operator(text) to service_role;
grant execute on function public.request_payout(uuid, text, numeric, numeric) to service_role;
grant execute on function public.cancel_payout_request(uuid, text) to service_role;
grant execute on function public.resolve_payout_request(uuid, text, text, text, text, text) to service_role;
